### PR TITLE
Update Docset URL and add more indexing

### PR DESCRIPTION
**Pull request by michaelblyons**
The indexing is not perfect, but it's still helpful.

### CODE REVIEW

**Comment by FichteFoll** [comment]
I tried this out in Zeal and it generall works, but there are some things that need to be improved and post-processed to make this more useful:

1. Parameters should be removed from symbol names.
1. Scrolling to the function definitions does not work. It scrolls to the beginning of the table instead. Could this be a zeal issue?
1. It would be nice if you could prepend the class for the various methods.
1. The index page is unstyled. Subpages have proper styling, however.
1. `layer0.*` on the theme page aren't matched.

Things that need to be excluded:
1. All settings on the Completions page are included twice.
1. Syntax examples on the syntax page
1. Menu locators on the Build Systems page.
1. The type for most settings (e.g. on the indentation page)
1. File extensions like `.sublime-syntax` on the syntax page

**Comment by michaelblyons** [comment]
Thanks FF.

1. Removing parameters should be easy.
2. I have that problem in Dash, too. I think it's a problem with tables. The anchor for the link target is definitely inside the cell with the relevant method/property.
3. Yes, that would be nice, but I do not know how without heavy pre-processing of the ST site.
4. Interesting. My "main page" is fine, but now I see that it's loading the CSS over the internet. I can fix it, but all this revolves around the current ST redirect from `/docs/` to `/docs/3/`. When they ditch that, I can drop at least half the build instructions.
5. Thanks. I do no theming, so I didn't know what was important.

For the exclusions: I think in order to get better, I need some kind of unit testing and write rules page-by-page rather than general rules.

**Comment by FichteFoll** [comment]
2) Seems like the anchors are put *before* the td tags. Moving them into the td where the function signature is listed makes it work on FireFox, at least.

.

4) It's just that index.html doesn't have its references to the stylesheet (and other locations) rewritten.

**Comment by michaelblyons** [comment]
2. Sorry I missed that. I'll see what I can do.

4. Yeah, I'm working on it now. I currently have to `wget` the index page a _second time_ and fix it separately from the other pages because of that HTTP 3XX.

**Comment by michaelblyons** [comment]
(1) and (4) are fixed. The others may take real HTML parsing and reconstruction.

**Comment by FichteFoll** [comment]
I fixed the anchors in tables using find & sed. Will PR to your branch.

**Comment by FichteFoll** [comment]
I forked it to https://github.com/SublimeText/sublime-text-docset instead, so we can maintain this on our own. Name suggestions appreciated. I'm very much interested in maintaining this, as I've been wanting to have a proper docset for ST for years and dashing provides a pretty solid base. We can also set up cron jobs using github actions to automatically build and update the docset.

I have addressed every point in my comment above and some more *except* prepending the class and module names for the API methods and properies. That will require some actual html parsing, probably using some Python script.

**Comment by michaelblyons** [comment]
Future comers: Most of the conversation here has been moved to https://github.com/SublimeText/sublime-text-docset

**Comment by malexer** [comment]
Great, I guess I am merging this PR.
I can add a link to https://github.com/SublimeText/sublime-text-docset into readme to redirect everybody to officially maintained version.
@FichteFoll does it sound good for you?

**Comment by FichteFoll** [comment]
Sure thing. Thanks.

**Pull request merged**
